{
 "title": "Seagate Drive Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Warranty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Retired Sector Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(seagate_retired_sectors_count) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Retired Sector Health (decrease -> degrade)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "avg(seagate_retired_sectors_count) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Read Error Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(seagate_read_error_rate) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Read Error Health (decrease -> degrade)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "avg(seagate_read_error_rate) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Seek Error Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg(seagate_seek_error_rate) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Seek Error Health (decrease -> degrade)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "avg(seagate_seek_error_rate) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Spin Up Time",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(seagate_spin_up_time) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Spin Up Time Health (decrease != degrade)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "avg(seagate_spin_up_time) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Spin Retry Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(seagate_spin_retry_count) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Spin Up Time Health (decrease != degrade)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "avg(seagate_spin_retry_count) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  { "title": "Physical Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Airflow Temp Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(seagate_airflow_temperature) without(raw, raw_2b)"
    }
   ]
  },
  {
   "title": "Airflow Temp Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "avg(seagate_airflow_temperature) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(seagate_temperature) without(raw)"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 38 },
   "targets": [
    {
     "expr": "avg(seagate_temperature) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Shock Sensor",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "seagate_shock_sensor_counter" }
   ]
  },
  {
   "title": "Shock Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 44 },
   "targets": [
    {
     "expr": "avg(seagate_shock_sensor_counter) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "Start/Stop Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "seagate_start_stop_count" }
   ]
  },
  {
   "title": "Start/Stop Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 50 },
   "targets": [
    {
     "expr": "avg(seagate_start_stop_count) without(raw, raw_2b)",
     "legendFormat": "{{host}} - {{handle}}"
    }
   ]
  },
  {
   "title": "IOEDC Health",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "seagate_ioedc_count" }
   ]
  }
 ]
}